version: "3"

services:
  frontend:
    build: ./VPM-ReactJS
    container_name: ReactApp-VPM
    ports:
      - "443:443"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - vpm-app
  backend:
    build: ./VPM-Nodejs
    container_name: RestServer-VPM
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - vpm-app
  database:
    image: mysql:8.0.33
    container_name: DataBase-VPM
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=devHugo
      - MYSQL_PASSWORD=1q2w3e
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - vpm-app
